spring:
  profiles.active: dev

elasticsearch:
  password:
  user:
  host: localhost
  port: 9200

---
spring:
  profiles: demo

elasticsearch:
  password: utz1kuxw98
  user: h8amddgsal
  host: lhm-search-demo-4880040604.eu-west-1.bonsaisearch.net
  port: 443