spring:
  profiles.active: dev

server.port: 8081

elasticsearch:
  password:
  user:
  host: localhost
  port: 9200

---
spring:
  profiles: demo

elasticsearch:
  password: 
  user: 
  host: 
  port: 443
